# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_name',
            new_name='discussion_title',
        ),
    ]
