# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ('date_started',),
            },
        ),
    ]
