# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='expert_in',
            field=models.CharField(default='Web Development', max_length=400),
        ),
        migrations.AddField(
            model_name='about',
            name='freelance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.CharField(default='English', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
