# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-expertise',)},
        ),
    ]
